version: '3'

services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: DockerfileReact
    volumes:
      - ./react:/usr/src/app
    command: sh -c "yarn run dev"
    ports:
      - 3000:3000
    stdin_open: true
  go:
    container_name: go-api
    build:
      context: .
      dockerfile: DockerfileGo
    volumes:
      - ./go:/api
    command: sh -c "go run main.go"
    ports:
      - 3001:3001
    tty: true